files:
  - source: '/Source/New/Modules/Slithin.Modules.I18N/Resources/Locales/[a-z_]*/strings.json'
    translation: /Source/New/Modules/Slithin.Modules.I18N/Resources/Locales/%two_letters_code%/%two_letters_code%.json
