name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Path: Source/Slithin/  
      Solution_Name: Source/Slithin/Slithin.csproj                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: Source/Slithin.Tests/Slithin.Tests.csproj               # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: Deployment/Windows-Store    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: Windows-Store.wapproj                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      SDK: Source/Slithin.Scripting.Interactive/Slithin.Scripting.Interactive.csproj    
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
        
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Publish Windows x86
      run: dotnet publish -c Release -r win-x86 -p:PublishReadyToRun=true --output ./Dist/Win-x86 $env:Solution_Name
        
    - name: Publish Windows x64
      run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true --output ./Dist/Win-x64 $env:Solution_Name

    - name: Publish OSX x64
      run: dotnet publish -c Release -r osx-x64 --output ./Dist/OSX-x64 $env:Solution_Name
        
    - name: Publish OSX Arm64
      run: dotnet publish -c Release -r osx.12-arm64 --output ./Dist/OSX_Arm64 $env:Solution_Name
      
    - name: Publish Linux x64
      run: dotnet publish -c Release -r linux-x64 --output ./Dist/Linux-x64 $env:Solution_Name
        
    - name: Installing dotnet-packaging deb
      run: dotnet tool install --global dotnet-deb
      
    - name: Installing dotnet-packaging rpm
      run: dotnet tool install --global dotnet-rpm
      
    - name: Creating Deb-Package
      run: dotnet deb -r linux-x64 -c Release -o ./Dist/Linux-x64-Deb
      working-directory: Source/Slithin/
      
    - name: Creating Rpm-Package
      run: dotnet rpm -r linux-x64 -c Release -o ./Dist/Linux-x64-Rpm
      working-directory: Source/Slithin/
        
    - name: Ziping Linux
      run: zip -r ./Dist/Linux-x64.zip ./Dist/Linux-x64
      
    - name: Ziping Windows
      run: zip -r ./Dist/Win-x64.zip ./Dist/Win-x64 && ./Dist/Win-x86.zip ./Dist/Win-x86
      
    - name: Ziping OSX
      run: zip -r ./Dist/OSX-x64.zip ./Dist/OSX-x64 && ./Dist/OSX_Arm64.zip ./Dist/OSX_Arm64
      
    - name: Generate Release
      run: gh release create v1.2.3 -F Source/Slithin/Changelog.txt ./Dist/*.zip
