on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Compile WebAssembly Standard Library
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        wasm-dir: /WASM/
    - name: npm install
      working-directory: $env:wasm-dir
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run asbuild

