on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Compile WebAssembly Standard Library
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      run: npm ci --no-audit WASM
    - name: Clean distribution files
      run: npm run clean
    - name: Test sources
      run: npm test
    - name: Build distribution files
      run: npm run build
      
    - name: npm install
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        cd WASM
        npm install --save @assemblyscript/loader
        npm install --save-dev assemblyscript
        npm install
        npm run asbuild

